server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emailer
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.example.com
    port: 587
    username: your-username
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rod:
  api:
    base-url: http://rod-api.example.com
  cache:
    ttl: 300000  # 5 minutes in milliseconds 